name: Download DragonRuby
description: |
  An action for downloading binaries (and if necessary C headers) of the DragonRuby Game Toolkit.

branding:
  icon: download
  color: red

inputs:
  version:
    description: Version to download
    default: 'latest'
  license_tier:
    description: Which license tier to download
    default: 'standard'

outputs:
  version:
    description: Version downloaded
    value: ${{ steps.download-dragonruby-version.outputs.version || steps.download-latest-dragonruby-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Download DragonRuby ${{ inputs.version }}-${{ inputs.license_tier }}
      id: download-dragonruby-version
      run: |
        download_dragonruby.sh ${{ inputs.version }} ${{ inputs.license_tier }}
        echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
      shell: bash
      if: ${{ inputs.version != 'latest' }}
    - name: Download latest DragonRuby (${{inputs.license_tier}})
      id: download-latest-dragonruby-version
      run: |
        latest_version=$(print_latest_dragonruby_version.sh)
        download_dragonruby.sh $latest_version ${{ inputs.license_tier }}
        echo "version=$latest_version" >> $GITHUB_OUTPUT
      shell: bash
      if: ${{ inputs.version == 'latest' }}
