name: Download DragonRuby
description: |
  An action for downloading binaries (and if necessary C headers) of the DragonRuby Game Toolkit to run tests and/or
  build C Extensions.

inputs:
  version:
    description: Version to download
    required: true

runs:
  using: "composite"
  steps:
    - name: Download DragonRuby ${{ inputs.version }}
      run: |
        base_url="https://github.com/kfischer-okarin/dragonruby-for-ci/releases/download/${{ inputs.version }}"
        filename="dragonruby-for-ci-${{ inputs.version }}-standard-linux-amd64.zip"
        curl -L -o dragonruby.zip $base_url/$filename
        unzip dragonruby.zip
        chmod u+x ./dragonruby
      shell: bash
