name: Download DragonRuby
description: |
  An action for downloading binaries (and if necessary C headers) of the DragonRuby Game Toolkit to run tests and/or
  build C Extensions.

inputs:
  version:
    description: Version to download
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Download DragonRuby ${{ inputs.version }}
      run: download_dragonruby.sh ${{ inputs.version }}
      shell: bash
