name: Download DragonRuby
description: |
  An action for downloading binaries (and if necessary C headers) of the DragonRuby Game Toolkit to run tests and/or
  build C Extensions.

inputs:
  version:
    description: Version to download
    default: 'latest'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Download DragonRuby ${{ inputs.version }}
      run: download_dragonruby.sh ${{ inputs.version }}
      shell: bash
      if: ${{ inputs.version != 'latest' }}
    - name: Download latest DragonRuby
      run: download_dragonruby.sh $(print_latest_dragonruby_version.sh)
      shell: bash
      if: ${{ inputs.version == 'latest' }}
